# Perform CentOS/RHEL related configurations
- name: Fail if CONTAINER_RUNTIME is not set to podman
  fail:
    msg: Only Podman is supported in CentOS/RHEL
  when: CONTAINER_RUNTIME != "podman"

- name: Enable SELinux
  ansible.posix.selinux:
    policy: targeted
    state: permissive
  become: yes
  when: ansible_selinux.status == "enabled"

# Remove any previous tripleo-repos to avoid version conflicts
# (see FIXME re oniguruma below)
- name: Remove any previous tripleo-repos to avoid version conflicts
  dnf:
    name: python*-tripleo-repos
    state: absent
  become: yes

- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest
    nobest: true
  become: yes

- name: Install podman
  dnf:
    name: podman
    state: present
  become: yes
  when: CONTAINER_RUNTIME == "podman"

- name: Install swtpm
  dnf:
    name: swtpm
    state: present
  become: yes
