---

- name: Remove virtualbmc directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    # From old systemd virtualbmc service
    - "/etc/virtualbmc"
    - "/var/log/virtualbmc"
    - "/root/.vbmc/"
    # Containerized version working dir
    - "{{ working_dir }}/virtualbmc"
  become: true

- name: Stop/disable the Virtual BMCs (virtualbmc >= 1.4.0+) on CentOS
  when:
    - ansible_os_family == "RedHat"
  service:
    name: "virtualbmc"
    state: "stopped" 
    enabled: false
  become: true

- name: Stop/disable the Virtual BMCs (virtualbmc >= 1.4.0+) on Ubuntu
  when:
    - ansible_distribution == 'Ubuntu' 
  shell: pkill vbmcd || true
  become: true
