collections:
- name: https://github.com/ansible-collections/kubernetes.core.git
  type: git
  version: 6.2.0
- name: https://github.com/ansible-collections/ansible.netcommon.git
  type: git
  version: v7.2.0
- name: https://github.com/ansible-collections/ansible.utils.git
  type: git
  version: v5.1.2
