---
- name: Teardown previous libvirt setup
  hosts: virthost
  connection: local
  gather_facts: true
  tasks:
    - import_role:
        name: common
    - import_role:
        name: libvirt
      vars:
        libvirt_action: "teardown"
    - import_role:
        name: virtbmc
      vars:
        virtbmc_action: "teardown"
    - import_role:
        name: nat64
      vars:
        nat64_action: "teardown"

